export const bigDistrict = [
  { id: 1, value: "Hà Nội" },
  { id: 2, value: "Hồ Chí Minh" },
  { id: 3, value: "Cần Thơ" },
  { id: 4, value: "Đà Nẵng" },
  { id: 5, value: "Đồng Nai" },
  { id: 6, value: "Hải Phòng" },
  { id: 7, value: "An Giang" },
  { id: 8, value: "Bà Rịa-Vũng Tàu" },
  { id: 9, value: "Bắc Giang" },
  { id: 10, value: "Bắc Kạn" },
  { id: 11, value: "Bạc Liêu" },
  { id: 12, value: "Bắc Ninh" },
  { id: 13, value: "Bến Tre" },
  { id: 14, value: "Bình Định" },
  { id: 15, value: "Bình Dương" },
  { id: 16, value: "Bình Phước" },
  { id: 17, value: "Bình Thuận" },
  { id: 18, value: "Cà Mau" },
  { id: 19, value: "Cao Bằng" },
  { id: 20, value: "Đắk Lắk" },
  { id: 21, value: "Đắk Nông" },
  { id: 22, value: "Điện Biên" },
  { id: 23, value: "Đồng Tháp" },
  { id: 24, value: "Gia Lai" },
  { id: 25, value: "Hà Giang" },
  { id: 26, value: "Hà Nam" },
  { id: 27, value: "Hà Tĩnh" },
  { id: 28, value: "Hải Dương" },
  { id: 29, value: "Hậu Giang" },
  { id: 30, value: "Hòa Bình" },
  { id: 31, value: "Hưng Yên" },
  { id: 32, value: "Khánh Hòa" },
  { id: 33, value: "Kiên Giang" },
  { id: 34, value: "Kon Tum" },
  { id: 35, value: "Lai Châu" },
  { id: 36, value: "Lâm Đồng" },
  { id: 37, value: "Lạng Sơn" },
  { id: 38, value: "Lào Cai" },
  { id: 39, value: "Long An" },
  { id: 40, value: "Nam Định" },
  { id: 41, value: "Nghệ An" },
  { id: 42, value: "Ninh Bình" },
  { id: 43, value: "Ninh Thuận" },
  { id: 44, value: "Phú Thọ" },
  { id: 45, value: "Phú Yên" },
  { id: 46, value: "Quảng Bình" },
  { id: 47, value: "Quảng Nam" },
  { id: 48, value: "Quảng Ngãi" },
  { id: 49, value: "Quảng Ninh" },
  { id: 50, value: "Quảng Trị" },
  { id: 51, value: "Sóc Trăng" },
  { id: 52, value: "Sơn La" },
  { id: 53, value: "Tây Ninh" },
  { id: 54, value: "Thái Bình" },
  { id: 55, value: "Thái Nguyên" },
  { id: 56, value: "Thanh Hóa" },
  { id: 57, value: "Thừa Thiên-Huế" },
  { id: 58, value: "Tiền Giang" },
  { id: 59, value: "Trà Vinh" },
  { id: 60, value: "Tuyên Quang" },
  { id: 61, value: "Vĩnh Long" },
  { id: 62, value: "Vĩnh Phúc" },
  { id: 63, value: "Yên Bái" },
];

const haNoi = [
  { id: 1, value: "Sơn Tây" },
  { id: 2, value: "Ba Đình" },
  { id: 3, value: "Bắc Từ Liêm" },
  { id: 4, value: "Cầu Giấy" },
  { id: 5, value: "Đống Đa" },
  { id: 6, value: "Hai Bà Trưng" },
  { id: 7, value: "Hà Đông" },
  { id: 8, value: "Hoàn Kiếm" },
  { id: 9, value: "Hoàng Mai" },
  { id: 10, value: "Long Biên" },
  { id: 11, value: "Nam Từ Liêm" },
  { id: 12, value: "Tây Hồ" },
  { id: 13, value: "Thanh Xuân" },
  { id: 14, value: "Ba Vì" },
  { id: 15, value: "Chương Mỹ" },
  { id: 16, value: "Đan Phượng" },
  { id: 17, value: "Đông Anh" },
  { id: 18, value: "Gia Lâm" },
  { id: 19, value: "Hoài Đức" },
  { id: 20, value: "Mê Linh" },
  { id: 21, value: "Mỹ Đức" },
  { id: 22, value: "Phú Xuyên" },
  { id: 23, value: "Phúc Thọ" },
  { id: 24, value: "Quốc Oai" },
  { id: 25, value: "Sóc Sơn" },
  { id: 26, value: "Thanh Trì" },
  { id: 27, value: "Thanh Oai" },
  { id: 28, value: "Thạch Thất" },
  { id: 29, value: "Thường Tín" },
  { id: 30, value: "Ứng Hòa" },
];
const hoChiMinh = [
  { id: 1, value: "Thủ Đức" },
  { id: 2, value: "District 1" },
  { id: 3, value: "District 3" },
  { id: 4, value: "District 4" },
  { id: 5, value: "District 5" },
  { id: 6, value: "District 6" },
  { id: 7, value: "District 7" },
  { id: 8, value: "District 8" },
  { id: 9, value: "District 10" },
  { id: 10, value: "District 11" },
  { id: 11, value: "District 12" },
  { id: 12, value: "Gò Vấp" },
  { id: 13, value: "Tân Bình" },
  { id: 14, value: "Tân Phú" },
  { id: 15, value: "Bình Thạnh" },
  { id: 16, value: "Phú Nhuận" },
  { id: 17, value: "Bình Tân" },
  { id: 18, value: "Củ Chi" },
  { id: 19, value: "Hóc Môn" },
  { id: 20, value: "Bình Chánh" },
  { id: 21, value: "Nhà Bè" },
  { id: 22, value: "Cần Giờ" },
];
//index 2
const canTho = [
  { id: 1, value: "Bình Thủy" },
  { id: 2, value: "Cái Răng" },
  { id: 3, value: "Ninh Kiều" },
  { id: 4, value: "Ô Môn" },
  { id: 5, value: "Thốt Nốt" },
  { id: 6, value: "Cờ Đỏ" },
  { id: 7, value: "Phong Điền" },
  { id: 8, value: "Thới Lai" },
  { id: 9, value: "Vĩnh Thạnh" },
];

const daNang = [
  { id: 1, value: "Cẩm Lệ" },
  { id: 2, value: "Hải Châu" },
  { id: 3, value: "Hòa Vang" },
  { id: 4, value: "Liên Chiểu" },
  { id: 5, value: "Ngũ Hành Sơn" },
  { id: 6, value: "Sơn Trà" },
  { id: 7, value: "Thanh Khê" },
  { id: 8, value: "Hoàng Sa" },
];
const dongNai = [
  { id: 1, value: "Biên Hòa" },
  { id: 2, value: "Long Khánh" },
  { id: 3, value: "Cẩm Mỹ" },
  { id: 4, value: "Định Quán" },
  { id: 5, value: "Long Thành" },
  { id: 6, value: "Nhơn Trạch" },
  { id: 7, value: "Tân Phú" },
  { id: 8, value: "Thống Nhất" },
  { id: 9, value: "Trảng Bom" },
  { id: 10, value: "Vĩnh Cửu" },
  { id: 11, value: "Xuân Lộc" },
];

const haiPhong = [
  { id: 1, value: "Dương Kinh" },
  { id: 2, value: "Đồ Sơn" },
  { id: 3, value: "Hải An" },
  { id: 4, value: "Kiến An" },
  { id: 5, value: "Hồng Bàng" },
  { id: 6, value: "Ngô Quyền" },
  { id: 7, value: "Lê Chân" },
  { id: 8, value: "An Dương" },
  { id: 9, value: "An Lão" },
  { id: 10, value: "Bạch Long Vĩ" },
  { id: 11, value: "Cát Hải" },
  { id: 12, value: "Kiến Thụy" },
  { id: 13, value: "Tiên Lãng" },
  { id: 14, value: "Vĩnh Bảo" },
  { id: 15, value: "Thủy Nguyên" },
];

const anGiang = [
  { id: 1, value: "Châu Đốc" },
  { id: 2, value: "Long Xuyên" },
  { id: 3, value: "Tân Châu" },
  { id: 4, value: "An Phú" },
  { id: 5, value: "Châu Phú" },
  { id: 6, value: "Châu Thành" },
  { id: 7, value: "Chợ Mới" },
  { id: 8, value: "Phú Tân" },
  { id: 9, value: "Thoại Sơn" },
  { id: 10, value: "Tịnh Biên" },
  { id: 11, value: "Tri Tôn" },
];

const baRiaVungTau = [
  { id: 1, value: "Bà Rịa" },
  { id: 2, value: "Vũng Tàu" },
  { id: 3, value: "Phú Mỹ" },
  { id: 4, value: "Châu Đức" },
  { id: 5, value: "Côn Đảo" },
  { id: 6, value: "Đất Đỏ" },
  { id: 7, value: "Long Điền" },
  { id: 8, value: "Xuyên Mộc" },
];
const bacGiang = [
  { id: 1, value: "Bắc Giang" },
  { id: 2, value: "Hiệp Hòa" },
  { id: 3, value: "Lạng Giang" },
  { id: 4, value: "Lục Nam" },
  { id: 5, value: "Lục Ngạn" },
  { id: 6, value: "Sơn Động" },
  { id: 7, value: "Tân Yên" },
  { id: 8, value: "Việt Yên" },
  { id: 9, value: "Yên Dũng" },
  { id: 10, value: "Yên Thế" },
];

const bacKan = [
  { id: 1, value: "Bắc Kạn" },
  { id: 2, value: "Ba Bể" },
  { id: 3, value: "Bạch Thông" },
  { id: 4, value: "Chợ Đồn" },
  { id: 5, value: "Chợ Mới" },
  { id: 6, value: "Na Rì" },
  { id: 7, value: "Ngân Sơn" },
  { id: 8, value: "Pác Nặm" },
];
const bacLieu = [
  { id: 1, value: "Bạc Liêu" },
  { id: 2, value: "Giá Rai" },
  { id: 3, value: "Đông Hải" },
  { id: 4, value: "Hòa Binh" },
  { id: 5, value: "Hồng Dân" },
  { id: 6, value: "Phước Long" },
  { id: 7, value: "Vĩnh Lợi" },
];
const bacNinh = [
  { id: 1, value: "Bắc Ninh" },
  { id: 2, value: "Từ Sơn" },
  { id: 3, value: "Gia Bình" },
  { id: 4, value: "Lương Tài" },
  { id: 5, value: "Quế Võ" },
  { id: 6, value: "Thuận Thành" },
  { id: 7, value: "Tiên Du" },
  { id: 8, value: "Yên Phong" },
];
const benTre = [
  { id: 1, value: "Bến Tre" },
  { id: 2, value: "Ba Tri" },
  { id: 3, value: "Bình Đại" },
  { id: 4, value: "Châu Thành" },
  { id: 5, value: "Chợ Lách" },
  { id: 6, value: "Giồng Trôm" },
  { id: 7, value: "Mỏ Cày Bắc" },
  { id: 8, value: "Mỏ Cày Nam" },
  { id: 9, value: "Thạnh Phú" },
];
const binhDinh = [
  { id: 1, value: "Quy Nhơn" },
  { id: 2, value: "An Nhơn" },
  { id: 3, value: "Hoài Nhơn" },
  { id: 4, value: "An Lão" },
  { id: 5, value: "Hoài Ân" },
  { id: 6, value: "Phù Cát" },
  { id: 7, value: "Phù Mỹ" },
  { id: 8, value: "Tuy Phước" },
  { id: 9, value: "Tây Sơn" },
  { id: 10, value: "Vân Canh" },
  { id: 11, value: "Vĩnh Thạnh" },
];
const binhDuong = [
  { id: 1, value: "Thủ Dầu Một" },
  { id: 2, value: "Dĩ An" },
  { id: 3, value: "Thuận An" },
  { id: 4, value: "Bến Cát" },
  { id: 5, value: "Tân Uyên" },
  { id: 6, value: "Bàu Bàng" },
  { id: 7, value: "Bắc Tân Uyên" },
  { id: 8, value: "Dầu Tiếng" },
  { id: 9, value: "Phú Giáo" },
];

const binhPhuoc = [
  { id: 1, value: "Đồng Xoài" },
  { id: 2, value: "Bình Long" },
  { id: 3, value: "Phước Long" },
  { id: 4, value: "Bù Đăng" },
  { id: 5, value: "Bù Đốp" },
  { id: 6, value: "Bù Gia Mập" },
  { id: 7, value: "Phú Riềng" },
  { id: 8, value: "Chơn Thành" },
  { id: 9, value: "Đồng Phú" },
  { id: 10, value: "Hớn Quản" },
  { id: 11, value: "Lộc Ninh" },
];
const binhThuan = [
  { id: 1, value: "Phan Thiết" },
  { id: 2, value: "La Gi" },
  { id: 3, value: "Bắc Bình" },
  { id: 4, value: "Đức Linh" },
  { id: 5, value: "Hàm Thuận Bắc" },
  { id: 6, value: "Hàm Thuận Nam" },
  { id: 7, value: "Hàm Tân" },
  { id: 8, value: "Phú Quý" },
  { id: 9, value: "Tánh Linh" },
  { id: 10, value: "Tuy Phong" },
];

const caMau = [
  { id: 1, value: "Cà Mau" },
  { id: 2, value: "Cái Nước" },
  { id: 3, value: "Đầm Dơi" },
  { id: 4, value: "Năm Căn" },
  { id: 5, value: "Ngọc Hiển" },
  { id: 6, value: "Phú Tân" },
  { id: 7, value: "Thới Bình" },
  { id: 8, value: "Trần Văn Thời" },
  { id: 9, value: "U Minh" },
];

const caoBang = [
  { id: 1, value: "Cao Bằng" },
  { id: 2, value: "Bảo Lạc" },
  { id: 3, value: "Bảo Lâm" },
  { id: 4, value: "Hạ Lang" },
  { id: 5, value: "Hà Quảng" },
  { id: 6, value: "Hòa An" },
  { id: 7, value: "Nguyên Bình" },
  { id: 8, value: "Quảng Hòa" },
  { id: 9, value: "Thạch An" },
  { id: 10, value: "Trùng Khánh" },
];
const dakLak = [
  { id: 1, value: "Buôn Ma Thuột" },
  { id: 2, value: "Buôn Hồ" },
  { id: 3, value: "Buôn Đôn" },
  { id: 4, value: "Cư Kuin" },
  { id: 5, value: "Cư M'gar" },
  { id: 6, value: "Ea H'leo" },
  { id: 7, value: "Ea Kar" },
  { id: 8, value: "Ea Súp" },
  { id: 9, value: "Krông Ana" },
  { id: 10, value: "Krông Bông" },
  { id: 11, value: "Krông Búk" },
  { id: 12, value: "Krông Năng" },
  { id: 13, value: "Krông Pắc" },
  { id: 14, value: "Lắk" },
  { id: 15, value: "M'Drắk" },
];
const dakNong = [
  { id: 1, value: "Gia Nghĩa" },
  { id: 2, value: "Cư Jút" },
  { id: 3, value: "Đăk Glong" },
  { id: 4, value: "Đăk Mil" },
  { id: 5, value: "Đăk R'Lấp" },
  { id: 6, value: "Đăk Song" },
  { id: 7, value: "Krông Nô" },
  { id: 8, value: "Tuy Đức" },
];
const dienBien = [
  { id: 1, value: "Điện Biên Phủ" },
  { id: 2, value: "Mường Lay" },
  { id: 3, value: "Điện Biên" },
  { id: 4, value: "Điện Biên Đông" },
  { id: 5, value: "Mường Ảng" },
  { id: 6, value: "Mường Chà" },
  { id: 7, value: "Mường Nhé" },
  { id: 8, value: "Nậm Pồ" },
  { id: 9, value: "Tủa Chùa" },
  { id: 10, value: "Tuần Giáo" },
];
const dongThap = [
  { id: 1, value: "Cao Lãnh" },
  { id: 2, value: "Hồng Ngự" },
  { id: 3, value: "Sa Đéc" },
  { id: 4, value: "Cao Lãnh" },
  { id: 5, value: "Châu Thành" },
  { id: 6, value: "Hồng Ngự" },
  { id: 7, value: "Lai Vung" },
  { id: 8, value: "Lấp Vò" },
  { id: 9, value: "Tam Nông" },
  { id: 10, value: "Tân Hồng" },
  { id: 11, value: "Thanh Bình" },
  { id: 12, value: "Tháp Mười" },
];
const giaLai = [
  { id: 1, value: "Pleiku" },
  { id: 2, value: "An Khê" },
  { id: 3, value: "Ayun Pa" },
  { id: 4, value: "Chư Păh" },
  { id: 5, value: "Chư Prông" },
  { id: 6, value: "Chư Pưh" },
  { id: 7, value: "Chư Sê" },
  { id: 8, value: "Đắk Đoa" },
  { id: 9, value: "Đắk Pơ" },
  { id: 10, value: "Đức Cơ" },
  { id: 11, value: "Ia Grai" },
  { id: 12, value: "Ia Pa" },
  { id: 13, value: "K'Bang" },
  { id: 14, value: "Kông Chro" },
  { id: 15, value: "Krông Pa" },
  { id: 16, value: "Mang Yang" },
  { id: 17, value: "Phú Thiện" },
];
const haGiang = [
  { id: 1, value: "Hà Giang" },
  { id: 2, value: "Bắc Mê" },
  { id: 3, value: "Bắc Quang" },
  { id: 4, value: "Đồng Văn" },
  { id: 5, value: "Hoàng Su Phì" },
  { id: 6, value: "Mèo Vạc" },
  { id: 7, value: "Quản Bạ" },
  { id: 8, value: "Quang Bình" },
  { id: 9, value: "Vị Xuyên" },
  { id: 10, value: "Xín Mần" },
  { id: 11, value: "Yên Minh" },
];
const haNam = [
  { id: 1, value: "Phủ Lý" },
  { id: 2, value: "Duy Tiên" },
  { id: 3, value: "Bình Lục" },
  { id: 4, value: "Kim Bảng" },
  { id: 5, value: "Lý Nhân" },
  { id: 6, value: "Thanh Liêm" },
];
const haTinh = [
  { id: 1, value: "Hà Tĩnh" },
  { id: 2, value: "Hồng Lĩnh" },
  { id: 3, value: "Kỳ Anh " },
  { id: 4, value: "Cẩm Xuyên" },
  { id: 5, value: "Can Lộc" },
  { id: 6, value: "Đức Thọ" },
  { id: 7, value: "Hương Khê" },
  { id: 8, value: "Hương Sơn" },
  { id: 9, value: "Kỳ Anh" },
  { id: 10, value: "Lộc Hà" },
  { id: 11, value: "Nghi Xuân" },
  { id: 12, value: "Thạch Hà" },
  { id: 13, value: "Vũ Quang" },
];
const haiDuong = [
  { id: 1, value: "Hải Dương" },
  { id: 2, value: "Chí Linh" },
  { id: 3, value: "Bình Giang" },
  { id: 4, value: "Cẩm Giàng" },
  { id: 5, value: "Gia Lộc" },
  { id: 6, value: "Kim Thành" },
  { id: 7, value: "Kinh Môn" },
  { id: 8, value: "Nam Sách" },
  { id: 9, value: "Ninh Giang" },
  { id: 10, value: "Thanh Hà" },
  { id: 11, value: "Thanh Miện" },
  { id: 12, value: "Tứ Kỳ" },
];
const hauGiang = [
  { id: 1, value: "Vị Thanh" },
  { id: 2, value: "Ngã Bảy" },
  { id: 3, value: "Long Mỹ" },
  { id: 4, value: "Châu Thành" },
  { id: 5, value: "Châu Thành A" },
  { id: 6, value: "Long Mỹ" },
  { id: 7, value: "Phụng Hiệp" },
  { id: 8, value: "Vị Thủy" },
];
const hoaBinh = [
  "Hòa Bình",
  "Cao Phong",
  "Đà Bắc",
  "Kim Bôi",
  "Lạc Sơn",
  "Lạc Thủy",
  "Lương Sơn",
  "Mai Châu",
  "Tân Lạc",
  "Yên Thủy",
];
//index 30
const hungYen = [
  "Hưng Yên",
  "Mỹ Hào",
  "Ân Thi",
  "Khoái Châu",
  "Kim Động",
  "Phù Cừ",
  "Tiên Lữ",
  "Văn Giang",
  "Văn Lâm",
  "Yên Mỹ",
];
//index 31
const khanhHoa = [
  "Nha Trang",
  "Cam Ranh",
  "Ninh Hòa",
  "Cam Lâm",
  "Diên Khánh",
  "Khánh Sơn",
  "Khánh Vĩnh",
  "Trường Sa",
  "Vạn Ninh",
];
//index 32
const kienGiang = [
  "Rạch Giá",
  "Phú Quốc Island",
  "Hà Tiên",
  "An Biên",
  "An Minh",
  "Châu Thành",
  "Giang Thành",
  "Giồng Riềng",
  "Gò Quao",
  "Hòn Đất",
  "Kiên Hải Island",
  "Kiên Lương",
  "Tân Hiệp",
  "Vĩnh Thuận",
  "U Minh Thượng",
];
//index 33
const konTum = [
  "Kon Tum",
  "Đắk Glei",
  "Đắk Hà",
  "Đắk Tô",
  "Ia H'Drai",
  "Kon Plông",
  "Kon Rẫy",
  "Ngọc Hồi",
  "Sa Thầy",
  "Tu Mơ Rông",
];
// index 34
const laiChau = [
  "Lai Châu",
  "Mường Tè",
  "Nậm Nhùn",
  "Phong Thổ",
  "Sìn Hồ",
  "Tam Dương",
  "Than Uyên",
  "Tân Uyên",
];
//index 35
const lamDong = [
  "Bảo Lộc",
  "Da Lat",
  "Bảo Lâm",
  "Cát Tiên",
  "Đạ Huoai",
  "Đạ Tẻh",
  "Đam Rông",
  "Di Linh",
  "Đơn Dương",
  "Đức Trọng",
  "Lạc Dương",
  "Lâm Hà",
];
//index 36
const langSon = [
  "Lạng Sơn",
  "Bắc Sơn",
  "Bình Gia",
  "Cao Lộc",
  "Chi Lăng",
  "Đình Lập",
  "Hữu Lũng",
  "Lộc Bình",
  "Tràng Định",
  "Văn Lãng",
  "Văn Quan",
];
//index 37
const laoCai = [
  "Lào Cai",
  "Sa Pa",
  "Bắc Hà",
  "Bảo Thắng",
  "Bảo Yên",
  "Bát Xát",
  "Mường Khương",
  "Si Ma Cai",
  "Văn Bàn",
];
//index 38
const longAn = [
  "Tân An",
  "Kiến Tường",
  "Bến Lức",
  "Cần Đước",
  "Cần Giuộc",
  "Châu Thành",
  "Đức Hòa",
  "Đức Huệ",
  "Mộc Hóa",
  "Tân Hưng",
  "Tân Thạnh",
  "Tân Trụ",
  "Thạnh Hóa",
  "Thủ Thừa",
  "Vĩnh Hưng",
];
//index 39
const namDinh = [
  "Nam Định",
  "Giao Thủy",
  "Hải Hậu",
  "Mỹ Lộc",
  "Nam Trực",
  "Nghĩa Hưng",
  "Trực Ninh",
  "Vụ Bản",
  "Xuân Trường",
  "Ý Yên",
];
//index 40
const ngheAn = [
  "Vinh",
  "Cửa Lò",
  "Thái Hòa",
  "Hoàng Mai",
  "Anh Sơn",
  "Con Cuông",
  "Diễn Châu",
  "Đô Lương",
  "Hưng Nguyên",
  "Kỳ Sơn",
  "Nam Đàn",
  "Nghi Lộc",
  "Nghĩa Đàn",
  "Quế Phong",
  "Quỳ Châu",
  "Quỳ Hợp",
  "Quỳnh Lưu",
  "Tân Kỳ",
  "Thanh Chương",
  "Tương Dương",
  "Yên Thàn",
];
//index 41
const ninhBinh = [
  "Ninh Bình",
  "Tam Điệp",
  "Gia Viễn",
  "Hoa Lư",
  "Kim Sơn",
  "Nho Quan",
  "Yên Khánh",
  "Yên Mô",
];
//index 42
const ninhThuan = [
  "Phan Rang–Tháp Chàm",
  "Bác Ái",
  "Ninh Hải",
  "Ninh Phước",
  "Ninh Sơn",
  "Thuận Bắc",
  "Thuận Nam",
];
//index 43
const phuTho = [
  "Việt Trì",
  "Phú Thọ",
  "Cẩm Khê",
  "Đoan Hùng",
  "Hạ Hòa",
  "Lâm Thao",
  "Phù Ninh",
  "Tam Nông",
  "Tân Sơn",
  "Thanh Ba",
  "Thanh Sơn",
  "Thanh Thủy",
  "Yên Lập",
];
//index 44
const phuYen = [
  "Tuy Hòa",
  "Đông Hòa",
  "Sông Cầu",
  "Đồng Xuân",
  "Phú Hòa",
  "Sơn Hòa",
  "Sông Hinh",
  "Tây Hòa",
  "Tuy An",
];
//index 45
const quangBinh = [
  "Đồng Hới",
  "Ba Đồn",
  "Bố Trạch",
  "Lệ Thủy",
  "Minh Hóa",
  "Quảng Ninh",
  "Quảng Trạch",
  "Tuyên Hóa",
];
//index 46
const quangNam = [
  "Hội An",
  "Tam Kỳ",
  "Điện Bàn",
  "Bắc Trà My",
  "Duy Xuyên",
  "Đại Lộc",
  "Điện Bàn",
  "Đông Giang",
  "Hiệp Đức",
  "Nam Giang",
  "Nam Trà My",
  "Núi Thành",
  "Phú Ninh",
  "Phước Sơn",
  "Quế Sơn",
  "Tây Giang",
  "Thăng Bình",
  "Tiên Phước",
  "Nông Sơn",
];
//index 47
const quangNgai = [
  "Quảng Ngãi",
  "Đức Phổ",
  "Ba Tơ",
  "Bình Sơn",
  "Minh Long",
  "Mộ Đức",
  "Nghĩa Hành",
  "Sơn Hà",
  "Sơn Tây",
  "Sơn Tịnh",
  "Tây Trà",
  "Trà Bồng",
  "Tư Nghĩa",
  "Lý Sơn",
];
//index 48
const quangNinh = [
  "Hạ Long",
  "Uông Bí",
  "Móng Cái",
  "Cẩm Phả",
  "Quảng Yên",
  "Đông Triều",
  "Cô Tô",
  "Đầm Hà",
  "Hải Hà",
  "Vân Đồn",
  "Bình Liêu",
  "Ba Chẽ",
  "Tiên Yên",
];
//index 49
const quangTri = [
  "Đông Hà",
  "Quảng Trị",
  "Cam Lộ",
  "Cồn Cỏ",
  "Đa Krông",
  "Gio Linh",
  "Hải Lăng",
  "Hướng Hóa",
  "Triệu Phong",
  "Vĩnh Linh",
];
//index 50
const socTrang = [
  "Sóc Trăng",
  "Vĩnh Châu",
  "Ngã Năm",
  "Châu Thành",
  "Cù Lao Dung",
  "Kế Sách",
  "Long Phú",
  "Mỹ Tú",
  "Mỹ Xuyên",
  "Thạnh Trị",
  "Trần Đề",
];
//index 51
const sonLa = [
  "Sơn La",
  "Bắc Yên",
  "Mai Sơn",
  "Mộc Châu",
  "Mường La",
  "Phù Yên",
  "Quỳnh Nhai",
  "Sông Mã",
  "Sốp Cộp",
  "Thuận Châu",
  "Vân Hồ",
  "Yên Châu",
];
//index 52
const tayNinh = [
  "Tây Ninh",
  "Hòa Thành",
  "Trảng Bàng",
  "Bến Cầu",
  "Châu Thành",
  "Dương Minh Châu",
  "Gò Dầu",
  "Tân Biên",
  "Tân Châu",
];
//index 53
const thaiBinh = [
  "Thái Bình",
  "Đông Hưng",
  "Hưng Hà",
  "Kiến Xương",
  "Quỳnh Phụ",
  "Thái Thụy",
  "Tiền Hải",
  "Vũ Thư",
];
//index 54
const thaiNguyen = [
  "Thái Nguyên",
  "Sông Công",
  "Phổ Yên",
  "Đại Từ",
  "Định Hóa",
  "Đồng Hỷ",
  "Phú Bình",
  "Phú Lương",
  "Võ Nhai",
];
//index 55
const thanhHoa = [
  "Thanh Hóa",
  "Sầm Sơn",
  "Bỉm Sơn",
  "Nghi Sơn",
  "Bá Thước",
  "Cẩm Thủy",
  "Đông Sơn",
  "Hà Trung",
  "Hậu Lộc",
  "Hoằng Hóa",
  "Lang Chánh",
  "Mường Lát",
  "Nga Sơn",
  "Ngọc Lặc",
  "Như Thanh",
  "Như Xuân",
  "Nông Cống",
  "Quan Hóa",
  "Quan Sơn",
  "Quảng Xương",
  "Thạch Thành",
  "Thiệu Hóa",
  "Thọ Xuân",
  "Thường Xuân",
  "Triệu Sơn",
  "Vĩnh Lộc",
  "Yên Định",
];
//index 56
const thuaThienHue = [
  "Huế",
  "Hương Thủy",
  "Hương Trà",
  "A Lưới",
  "Nam Đông",
  "Phong Điền",
  "Phú Lộc",
  "Phú Vang",
  "Quảng Điền",
];
//index 57
const tienGiang = [
  "Mỹ Tho",
  "Cai Lậy",
  "Gò Công",
  "Cái Bè",
  "Cai Lậy",
  "Châu Thành",
  "Chợ Gạo",
  "Gò Công Đông",
  "Gò Công Tây",
  "Tân Phú Đông",
  "Tân Phước",
];
//index 58
const traVinh = [
  "Trà Vinh",
  "Duyên Hải",
  "Càng Long",
  "Cầu Kè",
  "Cầu Ngang",
  "Châu Thành",
  "Duyên Hải",
  "Tiểu Cần",
  "Trà Cú",
];
//index 59
const tuyenQuang = [
  "Tuyên Quang",
  "Chiêm Hoá",
  "Hàm Yên",
  "Lâm Bình",
  "Na Hang",
  "Sơn Dương",
  "Yên Sơn",
];
//index 60
const vinhLong = [
  "Vĩnh Long",
  "Bình Minh",
  "Bình Tân",
  "Long Hồ",
  "Mang Thít",
  "Tam Bình",
  "Trà Ôn",
  "Vũng Liêm",
];
//index 61
const vinhPhuc = [
  "Vĩnh Yên",
  "Phúc Yên",
  "Sông Lô",
  "Bình Xuyên",
  "Lập Thạch",
  "Tam Đảo",
  "Tam Dương",
  "Vĩnh Tường",
  "Yên Lạc",
];
//index 62
const yenBai = [
  "Yên Bái",
  "Nghĩa Lộ",
  "Lục Yên",
  "Mù Cang Chải",
  "Trạm Tấu",
  "Trấn Yên",
  "Văn Chấn",
  "Văn Yên",
  "Yên Bình  ",
];

//2급 행정구 배열
export const smallDistrict1 = [
  haNoi,
  hoChiMinh,
  canTho,
  daNang,
  dongNai,
  haiPhong,
  anGiang,
  baRiaVungTau,
  bacGiang,
  bacKan,
  bacLieu,
  bacNinh,
  benTre,
  binhDinh,
  binhDuong,
  binhPhuoc,
  binhThuan,
  caMau,
  caoBang,
  dakLak,
  dakNong,
  dienBien,
  dongThap,
  giaLai,
  haGiang,
  haNam,
  haTinh,
  haiDuong,
  hauGiang,
  hoaBinh,
  hungYen,
  khanhHoa,
  kienGiang,
  konTum,
  laiChau,
  lamDong,
  langSon,
  laoCai,
  longAn,
  namDinh,
  ngheAn,
  ninhBinh,
  ninhThuan,
  phuTho,
  phuYen,
  quangBinh,
  quangNam,
  quangNgai,
  quangNinh,
  quangTri,
  socTrang,
  sonLa,
  tayNinh,
  thaiBinh,
  thaiNguyen,
  thanhHoa,
  thuaThienHue,
  tienGiang,
  traVinh,
  tuyenQuang,
  vinhLong,
  vinhPhuc,
  yenBai,
];

export const smallDistrict2 = [
  { id: 1, value: haNoi },
  { id: 2, value: hoChiMinh },
  // { id: 11, value: "Bạc Liêu" },
  // { id: 12, value: "Bắc Ninh" },
  // { id: 13, value: "Bến Tre" },
  // { id: 14, value: "Bình Định" },
  // { id: 15, value: "Bình Dương" },
  // { id: 16, value: "Bình Phước" },
  // { id: 17, value: "Bình Thuận" },
  // { id: 18, value: "Cà Mau" },
  // { id: 19, value: "Cao Bằng" },
  // { id: 20, value: "Đắk Lắk" },
  // { id: 21, value: "Đắk Nông" },
  // { id: 22, value: "Điện Biên" },
  // { id: 23, value: "Đồng Tháp" },
  // { id: 24, value: "Gia Lai" },
  // { id: 25, value: "Hà Giang" },
  // { id: 26, value: "Hà Nam" },
  // { id: 27, value: "Hà Tĩnh" },
  // { id: 28, value: "Hải Dương" },
  // { id: 29, value: "Hậu Giang" },
  // { id: 30, value: "Hòa Bình" },
  // { id: 31, value: "Hưng Yên" },
  // { id: 32, value: "Khánh Hòa" },
  // { id: 33, value: "Kiên Giang" },
  // { id: 34, value: "Kon Tum" },
  // { id: 35, value: "Lai Châu" },
  // { id: 36, value: "Lâm Đồng" },
  // { id: 37, value: "Lạng Sơn" },
  // { id: 38, value: "Lào Cai" },
  // { id: 39, value: "Long An" },
  // { id: 40, value: "Nam Định" },
  // { id: 41, value: "Nghệ An" },
  // { id: 42, value: "Ninh Bình" },
  // { id: 43, value: "Ninh Thuận" },
  // { id: 44, value: "Phú Thọ" },
  // { id: 45, value: "Phú Yên" },
  // { id: 46, value: "Quảng Bình" },
  // { id: 47, value: "Quảng Nam" },
  // { id: 48, value: "Quảng Ngãi" },
  // { id: 49, value: "Quảng Ninh" },
  // { id: 50, value: "Quảng Trị" },
  // { id: 51, value: "Sóc Trăng" },
  // { id: 52, value: "Sơn La" },
  // { id: 53, value: "Tây Ninh" },
  // { id: 54, value: "Thái Bình" },
  // { id: 55, value: "Thái Nguyên" },
  // { id: 56, value: "Thanh Hóa" },
  // { id: 57, value: "Thừa Thiên-Huế" },
  // { id: 58, value: "Tiền Giang" },
  // { id: 59, value: "Trà Vinh" },
  // { id: 60, value: "Tuyên Quang" },
  // { id: 61, value: "Vĩnh Long" },
  // { id: 62, value: "Vĩnh Phúc" },
  // { id: 63, value: "Yên Bái" },
];
